package algorithms.Exercises.Exercise_1_3;

/**
 * Exercise 1.3.46
 * 
 * <p>
 * <i>Forbidden triple for stack generability</i>. Prove that a permutation can
 * be generated by a stack (as in the previous question) if and only if it has
 * no forbidden triple (𝑎, 𝑏, 𝑐) such that 𝑎 < 𝑏 < 𝑐 with 𝑐 first, 𝑎
 * second, and 𝑏 third (possibly with other intervening integers between 𝑐 and
 * 𝑎 and between 𝑎 and 𝑏).
 * </p>
 * <p>
 * Partial solution: Suppose that there is a forbidden triple (𝑎, 𝑏, 𝑐). Item
 * 𝑐 is popped before 𝑎 and 𝑏, but 𝑎 and 𝑏 are pushed before 𝑐. Thus, when
 * 𝑐 is pushed, both 𝑎 and 𝑏 are on the stack. Therefore, 𝑎 cannot be popped
 * before 𝑏.
 * </p>
 */
public class Exercise_1_3_46 {
    public static void main(String[] args) {
    }
}
