/*
 * This source file was generated by the Gradle 'init' task
 */
package algorithms;

import java.io.FileInputStream;
import java.io.IOException;

public class App {
    public static String getGreeting() {
        return "Hello, World!";
    }

    public static void main(String[] args) throws IOException {
        String[] binarySearchArgs = { "src/data/algs4/tinyW.txt" };
        System.setIn(new FileInputStream("src/data/algs4/tinyT.txt"));
        BinarySearch.main(binarySearchArgs);
    }
}
