/*
 * This source file was generated by the Gradle 'init' task
 */
package algorithms;

import edu.princeton.cs.algs4.StdOut;

public class App {
    public static String getGreeting() {
        return "Hello, World!";
    }

    public static void main(String[] args) {
        StdOut.println(getGreeting());
    }
}
